#!/usr/bin/env bash

SWIFT_VERSION=3.0.1

echo "Swift $SWIFT_VERSION Continuous Integration";

# Determine OS
UNAME=`uname`;
if [[ $UNAME == "Darwin" ]];
then
    OS="macos";
else
    if [[ $UNAME == "Linux" ]];
    then
        UBUNTU_RELEASE=`lsb_release -a 2>/dev/null`;
        if [[ $UBUNTU_RELEASE == *"15.10"* ]];
        then
            OS="ubuntu1510";
        else
            OS="ubuntu1404";
        fi
    else
        echo "Unsupported Operating System: $UNAME";
    fi
fi
echo "🖥 Operating System: $OS";

if [[ $OS == "macos" ]];
then
    brew update
    brew install mongodb
    brew services start mongodb
else
    echo "📚 Installing Mongo tools"
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
    echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
    sudo apt-get update
    sudo apt-get install mongodb-org-shell mongodb-org-tools
    echo "Create data directory"
    mkdir -p Tools/storage/mongodb/dbdockerssl
    echo "Create Docker Container with MongoDB"
    docker pull mongo:latest
    docker run -p 27017:27017 -v $PWD/Tools/storage/mongodb/dbdockerssl:/data/db --name mongokittenplain -d mongo mongod

    echo "🐦 Installing Swift";
    eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
fi

echo "Prepare Data"
mongoimport --host localhost --port 27017 --db=mongokitten-unittest --collection=zips --drop Tools/zips.json 

echo "📅 Version: `swift --version`";
echo "🚀 Building";
swift build
if [[ $? != 0 ]]; 
then 
    echo "❌  Build failed";
    exit 1; 
fi

echo "💼 Building Release";
swift build -c release
if [[ $? != 0 ]]; 
then 
    echo "❌  Build for release failed";
    exit 1; 
fi

echo "🔎 Testing";

swift test
if [[ $? != 0 ]]; 
then 
    echo "❌ Tests failed";
    exit 1; 
fi

echo "✅ Done"